parameters:
    database_host: '%env(ARTIFAKT_MYSQL_HOST)%'
    database_port: '%env(ARTIFAKT_MYSQL_PORT)%'
    database_name: '%env(ARTIFAKT_MYSQL_DATABASE_NAME)%'
    database_user: '%env(ARTIFAKT_MYSQL_USER)%'
    database_password: '%env(ARTIFAKT_MYSQL_PASSWORD)%'
    mailer_transport: '%env(mailer_transport)%'
    mailer_host: '%env(mailer_host)%'
    mailer_user: '%env(mailer_user)%'
    mailer_password: '%env(mailer_password)%'
    secret: '%env(secret)%'